Made Punctuation, Grammar and other changes in the documentation - Issue 104
avinashkranjan/Friday pull request #121
Opened 2021-03-26 21:24 UTC by devTejas

# Description

Removed all the grammatical, punctuation errors from the documentation and other readme files.

## Fixes #(104)

![Screenshot (208)](https://user-images.githubusercontent.com/55909123/112693810-3e400e00-8ea7-11eb-9e08-5b6fe1009692.png)
![Screenshot (209)](https://user-images.githubusercontent.com/55909123/112693813-3f713b00-8ea7-11eb-833b-21d92d0ece00.png)

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Friday/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Added new sections such as `Major Issues and Updates` and `Resources`

## Checklist:

- [x] My changes follows the style guidelines of this project.
- [x] I have performed a self-review of my own changes.
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

2021-04-06 05:55 UTC, devTejas commented
Hey @avinashkranjan, I have resolved the conflicts and made a new branch.
Thank you.

2021-04-08 13:25 UTC, hareshnayak approved these changes
There is no change in file " CODE_OF_CONDUCT.md "
You have added only one word "the" in " CONTRIBUTING.md "
Other two file have some minor changes.
If you want to contribute to the document you could write some original content you find better for the doc.

For now I am approving the PR , but it would be appreciated if you could provide more original content

2021-04-08 15:48 UTC, avinashkranjan requested changes

2021-04-08 15:48 UTC, avinashkranjan commented on README.md
> +
@devTejas Kinly Make Changes in the New `README` as README.md as been updated..

2021-04-15 07:26 UTC, avinashkranjan commented
No Response Closing this `PR`

2021-04-15 07:26 UTC, closed without merging