Readme enhanced
avinashkranjan/Friday pull request #154
Opened 2021-04-15 11:32 UTC by anirudhsai20

# Description

I have added a list of all the Open Source programs in which this project was listed in and I also corrected a minor grammatical error.

## Fixes #131 

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Friday/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

2021-04-16 08:27 UTC, avinashkranjan requested changes
Hey @anirudhsai20 Kindly Add SWoC too, and this Project has been part of that program too...

2021-04-16 08:33 UTC, anirudhsai20 commented
Sure. I will add SWOC as well.

2021-04-16 08:50 UTC, anirudhsai20 commented
I have made the necessary changes.

2021-04-16 20:12 UTC, avinashkranjan requested changes
Kindly Reduce the Size and Keep them in Same Line and add an anchor tag linking to their official websites

2021-04-17 15:16 UTC, anirudhsai20 commented
Hi! I have made the required changes. Kindly, check if you are satisfied with them.

2021-04-19 07:02 UTC, avinashkranjan requested changes
Make the asked changes

2021-04-19 07:02 UTC, avinashkranjan commented on README.md
> + <img  width="300" height="70" src="https://raw.githubusercontent.com/GirlScriptSummerOfCode/MentorshipProgram/master/GSsoc%20Type%20Logo%20Black.png">
`[<img width="300" height="70" src="https://raw.githubusercontent.com/GirlScriptSummerOfCode/MentorshipProgram/master/GSsoc%20Type%20Logo%20Black.png">](https://gssoc.girlscript.tech/)`

Change this code to this to link the image to the website

2021-04-19 07:02 UTC, avinashkranjan commented on README.md
> + <img  width="100" height="100" src="https://swoc.tech/img/logo-2.png">
Follow the Same here

2021-04-24 04:45 UTC, anirudhsai20 commented
Hi! Sorry I made a lot of mistakes. I have corrected them now. Please check if they require any other changes.

2021-04-24 06:32 UTC, avinashkranjan approved these changes

2021-04-24 06:32 UTC, merged